Repository capactio/capact, pull requests merged in 2021-07, with the labels that each got.

#380 Bump kind version
  hack/lib/const.sh
Labels: area/ci, dependencies

#372 Add capact env create kind command
  cmd/cli/cmd/environment/create/create.go
  cmd/cli/cmd/environment/create/kind.go
  cmd/cli/cmd/environment/delete/delete.go
  cmd/cli/cmd/environment/delete/kind.go
  cmd/cli/cmd/environment/environment.go
  cmd/cli/cmd/root.go
  cmd/cli/docs/capact.md
  cmd/cli/docs/capact_environment.md
  cmd/cli/docs/capact_environment_create.md
  cmd/cli/docs/capact_environment_create_kind.md
  cmd/cli/docs/capact_environment_delete.md
  cmd/cli/docs/capact_environment_delete_kind.md
  go.mod
  go.sum
  internal/cli/environment/create/kind.go
  internal/cli/environment/create/kind_defaults.go
  internal/cli/environment/delete/kind.go
Labels: area/cli, area/documentation, enhancement

#381 [e2e] Unlock TypeInstances before deleting them
  test/e2e/hub_test.go
Labels: area/ci, bug, size/XS

#383 Introduce capact install command
  cmd/cli/cmd/install.go
  cmd/cli/cmd/root.go
  cmd/cli/cmd/upgrade.go
  cmd/cli/docs/capact.md
  cmd/cli/docs/capact_install.md
  cmd/populator/cmd/register/ocf_manifests.go
  go.mod
  go.sum
  internal/cli/capact/build.go
  internal/cli/capact/capact.go
  internal/cli/capact/components.go
  internal/cli/capact/defaults.go
  internal/cli/capact/helmhelper.go
  internal/cli/capact/k8s.go
  internal/cli/capact/kind.go
  internal/cli/capact/os.go
  internal/cli/capact/parameters.go
  internal/cli/install/install.go
  internal/cli/upgrade/upgrade.go
  internal/cli/upgrade/upgrade_test.go
  internal/io/io.go
  internal/tools.go
  pkg/engine/k8s/policy/types.go
  pkg/engine/k8s/policy/types_test.go
  pkg/hub/client/policy_merger.go
  pkg/sdk/dbpopulator/loader.go
Labels: area/cli, enhancement

#386 Prepare 0.4.0 release
  .github/workflows/branch-build.yaml
  deploy/kubernetes/charts/argo/Chart.yaml
  deploy/kubernetes/charts/capact/Chart.yaml
  deploy/kubernetes/charts/cert-manager/Chart.yaml
  deploy/kubernetes/charts/ingress-nginx/Chart.yaml
  deploy/kubernetes/charts/kubed/Chart.yaml
  deploy/kubernetes/charts/monitoring/Chart.yaml
  deploy/kubernetes/charts/neo4j/Chart.yaml
Labels: area/community

#387 Build argo-actions for local version
  internal/cli/capact/build.go
Labels: area/cli, bug

#390 Post release cleanup
  README.md
  deploy/kubernetes/charts/capact/charts/hub-local/templates/old-service.yaml
Labels: area/documentation, area/hub

#391 Parameterize the express body size limit
  hub-js/README.md
  hub-js/src/config.ts
  hub-js/src/index.ts
Labels: area/documentation, area/hub, enhancement

#394 Remove release warning from main README.md
  README.md
Labels: area/documentation

#389 Share Capact CLI between GH Action steps
  .github/workflows/branch-build.yaml
  .github/workflows/pr-build.yaml
Labels: area/ci, area/cli

#396 Set CAPCAT_BINARY env variable for all steps
  .github/workflows/pr-build.yaml
Labels: area/ci

#392 Replace deprecated `go get` with `go install`
  Dockerfile
  hack/gen-graphql-resources.sh
  hack/gen-k8s-resources.sh
Labels: area/ci, dependencies, enhancement

#402 Add support for typeRef in Interface parameters
  hack/gen_go_api_issue_exceptions.txt
  internal/cli/schema/static_schema_gen.go
  ocf-spec/0.0.1/examples/interface.yaml
  ocf-spec/0.0.1/schema/common/json-schema-type.json
  ocf-spec/0.0.1/schema/interface.json
  pkg/sdk/apis/0.0.1/types/types.generated.go
Labels: area/cli, area/ocf

#404 Use random tag for updates
  hack/dev-cluster-update.sh
Labels: area/cli, bug

#408 Increases Local hub resourcess during the upgrade
  internal/cli/upgrade/upgrade.go
Labels: area/cli, area/hub

#407 Allow using git as source for Terraform Runner, fix Engine panic
  Dockerfile
  go.mod
  go.sum
  hack/runners/terraform/providers.tf
  pkg/runner/terraform/runner.go
  pkg/runner/terraform/terraform.go
  pkg/sdk/renderer/argo/helpers.go
Labels: area/engine, area/hub-manifests, bug

#414 Add engine timeout, trigger infra
  .github/workflows/branch-build.yaml
  .github/workflows/pr-build.yaml
  deploy/kubernetes/charts/capact/charts/engine/templates/deployment.yaml
  deploy/kubernetes/charts/capact/charts/engine/values.yaml
  hack/ci/setup-env.sh
  hack/images/jinja2/README.md
  internal/k8s-engine/controller/config.go
Labels: area/ci, area/engine
