Repository capactio/capact, pull requests merged in 2021-11, with the labels that each got.

#543 Add GitLab REST API Runner
  Makefile
  cmd/gitlab-api-runner/README.md
  cmd/gitlab-api-runner/example-input/context.yaml
  cmd/gitlab-api-runner/example-input/create-project-args.yaml
  cmd/gitlab-api-runner/main.go
  go.mod
  go.sum
  hack/ci/setup-env.sh
  internal/cli/action/create.go
  pkg/runner/gitlab-api-runner/adapter.go
  pkg/runner/gitlab-api-runner/runner.go
  pkg/runner/gitlab-api-runner/types.go
  pkg/sdk/validation/interfaceio/validator.go
Labels: enhancement, area/cli, area/documentation

#549 Fix `hack/eks/install.sh` and add server auth mod for Argo
  deploy/kubernetes/charts/argo/values.yaml
  hack/eks/install.sh
  hack/eks/public-ingress-controller/install.sh
  hack/eks/terraform/templates/bastion_userdata.sh.tpl
  hack/eks/terraform/variables.tf
Labels: bug, area/documentation

#565 Update dependencies
  deploy/kubernetes/charts/cert-manager/Chart.lock
  deploy/kubernetes/charts/cert-manager/charts/cert-manager-v1.4.0.tgz
  deploy/kubernetes/charts/cert-manager/charts/cert-manager-v1.4.4.tgz
  deploy/kubernetes/charts/monitoring/Chart.lock
  deploy/kubernetes/charts/monitoring/Chart.yaml
  deploy/kubernetes/charts/monitoring/charts/kube-prometheus-stack-17.2.2.tgz
  deploy/kubernetes/charts/monitoring/charts/kube-prometheus-stack-20.0.1.tgz
  go.mod
  go.sum
  hub-js/package-lock.json
  hub-js/package.json
  hub-js/src/schema/local.ts
Labels: bug, dependencies, security

#566 Add fixed k3d version used for docker images
  cmd/cli/cmd/environment/create/k3d.go
  cmd/cli/cmd/root.go
Labels: bug, dependencies, area/cli

#568 Support GET requests and token auth in GitLab runner
  pkg/runner/gitlab-api-runner/runner.go
  pkg/runner/gitlab-api-runner/types.go
Labels: enhancement, area/hub-manifests

#569 Add investigation document for multi-cluster support in Capact
  docs/investigation/multi-cluster/README.md
  docs/investigation/multi-cluster/admiralty.md
  docs/investigation/multi-cluster/assets/capact-to-capact.svg
  docs/investigation/multi-cluster/assets/eu-foo.yaml
Labels: area/community, area/documentation
