Repository capactio/capact, pull requests merged in 2021-06, with the labels that each got.

#361 Enable all checks on the `main` branch
  .github/workflows/branch-build.yaml
  hack/ci/setup-env.sh
Labels: area/ci

#362 Fix jobs definition for branch-build.yaml
  .github/workflows/branch-build.yaml
  .github/workflows/pr-build.yaml
Labels: area/ci

#359 Update Capact CLI flag description
  cmd/cli/cmd/action/delete.go
  cmd/cli/cmd/upgrade.go
  cmd/cli/cmd/validate.go
  cmd/cli/docs/capact_action_delete.md
  cmd/cli/docs/capact_upgrade.md
  cmd/cli/docs/capact_validate.md
Labels: area/cli, area/documentation, enhancement

#363 Add note about the upcoming 0.4.0 release
  README.md
Labels: area/community, area/documentation, enhancement

#350 Add support for Workflow Policies
  deploy/kubernetes/charts/capact/charts/hub-public/values.yaml
  internal/k8s-engine/controller/action_service.go
  internal/ptr/string.go
  pkg/engine/k8s/policy/types.go
  pkg/engine/k8s/policy/types_test.go
  pkg/engine/k8s/policy/workflow.go
  pkg/engine/k8s/policy/zz_generated.deepcopy.go
  pkg/hub/api/graphql/public/helpers.go
  pkg/hub/api/graphql/public/helpers_test.go
  pkg/hub/client/policy_enforced_client.go
  pkg/hub/client/policy_merger.go
  pkg/hub/client/policy_merger_test.go
  pkg/sdk/apis/0.0.1/types/types.extend.go
  pkg/sdk/apis/0.0.1/types/zz_generated.deepcopy.go
  pkg/sdk/renderer/argo/dedicated_renderer.go
  pkg/sdk/renderer/argo/errors.go
  pkg/sdk/renderer/argo/helpers.go
  pkg/sdk/renderer/argo/options.go
  pkg/sdk/renderer/argo/renderer.go
  pkg/sdk/renderer/argo/renderer_test.go
  pkg/sdk/renderer/argo/testdata/TestRenderHappyPathWithCustomPolicies/Mattermost_with_AWS_RDS_install.golden.yaml
  pkg/sdk/renderer/argo/testdata/TestRenderHappyPathWithCustomPolicies/Workflow_policy_injects_additional_input_-_reference_by_ManifestRef.golden.yaml
  pkg/sdk/renderer/argo/testdata/TestRenderHappyPathWithCustomPolicies/Workflow_policy_injects_additional_input_-_reference_by_alias.golden.yaml
  pkg/sdk/renderer/argo/testdata/hub/implementation/app-stack/app1/install.yaml
  pkg/sdk/renderer/argo/testdata/hub/implementation/app-stack/app2/install.yaml
  pkg/sdk/renderer/argo/testdata/hub/implementation/aws/rds/postgresql/install.yaml
  pkg/sdk/renderer/argo/testdata/hub/implementation/aws/rds/postgresql/provision.yaml
  pkg/sdk/renderer/argo/types.go
Labels: area/engine, enhancement, size/XL

#370 Update populator docs
  cmd/populator/docs/populator_register-ocf-manifests.md
Labels: area/documentation, bug

#375 [Security] Update deps in hub-js
  hub-js/package-lock.json
  hub-js/package.json
  hub-js/src/types/README.md
  hub-js/src/types/neo4j-graphql-js/index.d.ts
  hub-js/src/types/neo4j-graphql-js/neo4j-graphql-js-test.ts
  hub-js/src/types/neo4j-graphql-js/package.json
  hub-js/src/types/neo4j-graphql-js/tsconfig.json
  hub-js/src/types/neo4j-graphql-js/tslint.json
Labels: area/hub, dependencies, security

#378 Add name for each query and mutation in Hub Go client
  .github/workflows/pr-build.yaml
  pkg/hub/client/local/client.go
  pkg/hub/client/public/client.go
Labels: area/hub, bug

#379 Add simple change to trigger CI
  .github/workflows/pr-build.yaml
  hack/ci/setup-env.sh
Labels: area/ci, bug
