Repository capactio/capact, pull requests merged in 2022-03, with the labels that each got.

#649 Add grpc investigation, change proto location, gen TS client, fix typo
  cmd/secret-storage-backend/README.md
  docs/investigation/local-hub-v2/README.md
  docs/investigation/local-hub-v2/ts-grpc/README.md
  docs/investigation/local-hub-v2/ts-grpc/grpc-gen/.gitignore
  docs/investigation/local-hub-v2/ts-grpc/grpc-gen/.prettierignore
  docs/investigation/local-hub-v2/ts-grpc/grpc-gen/README.md
  docs/investigation/local-hub-v2/ts-grpc/grpc-gen/client-official-await.ts
  docs/investigation/local-hub-v2/ts-grpc/grpc-gen/client-official.ts
  docs/investigation/local-hub-v2/ts-grpc/grpc-gen/client-ts-plugin.ts
  docs/investigation/local-hub-v2/ts-grpc/grpc-gen/config.ts
  docs/investigation/local-hub-v2/ts-grpc/grpc-gen/package-lock.json
  docs/investigation/local-hub-v2/ts-grpc/grpc-gen/package.json
  docs/investigation/local-hub-v2/ts-grpc/grpc-gen/proto/official/storage_backend.ts
  docs/investigation/local-hub-v2/ts-grpc/grpc-gen/proto/official/storage_backend/GetLockedByRequest.ts
  docs/investigation/local-hub-v2/ts-grpc/grpc-gen/proto/official/storage_backend/GetLockedByResponse.ts
  docs/investigation/local-hub-v2/ts-grpc/grpc-gen/proto/official/storage_backend/GetValueRequest.ts
  docs/investigation/local-hub-v2/ts-grpc/grpc-gen/proto/official/storage_backend/GetValueResponse.ts
  docs/investigation/local-hub-v2/ts-grpc/grpc-gen/proto/official/storage_backend/OnCreateRequest.ts
  docs/investigation/local-hub-v2/ts-grpc/grpc-gen/proto/official/storage_backend/OnCreateResponse.ts
  docs/investigation/local-hub-v2/ts-grpc/grpc-gen/proto/official/storage_backend/OnDeleteRequest.ts
  docs/investigation/local-hub-v2/ts-grpc/grpc-gen/proto/official/storage_backend/OnDeleteResponse.ts
  docs/investigation/local-hub-v2/ts-grpc/grpc-gen/proto/official/storage_backend/OnLockRequest.ts
  docs/investigation/local-hub-v2/ts-grpc/grpc-gen/proto/official/storage_backend/OnLockResponse.ts
  docs/investigation/local-hub-v2/ts-grpc/grpc-gen/proto/official/storage_backend/OnUnlockRequest.ts
  docs/investigation/local-hub-v2/ts-grpc/grpc-gen/proto/official/storage_backend/OnUnlockResponse.ts
  docs/investigation/local-hub-v2/ts-grpc/grpc-gen/proto/official/storage_backend/OnUpdateRequest.ts
  docs/investigation/local-hub-v2/ts-grpc/grpc-gen/proto/official/storage_backend/OnUpdateResponse.ts
  docs/investigation/local-hub-v2/ts-grpc/grpc-gen/proto/official/storage_backend/StorageBackend.ts
  docs/investigation/local-hub-v2/ts-grpc/grpc-gen/proto/official/storage_backend/TypeInstanceResourceVersion.ts
  docs/investigation/local-hub-v2/ts-grpc/grpc-gen/proto/ts-plugin/storage_backend.ts
  docs/investigation/local-hub-v2/ts-grpc/grpc-gen/tsconfig.json
  hack/gen-grpc-resources.sh
  hack/lib/const.sh
  hub-js/grpc/storage_backend.ts
  hub-js/proto/storage_backend.proto
  internal/secret-storage-backend/server.go
  internal/secret-storage-backend/server_test.go
  pkg/hub/api/grpc/storage_backend/client_test.go
  pkg/hub/api/grpc/storage_backend/storage_backend.pb.go
Labels: area/hub, area/documentation

#653 Create Helm chart for Secret Storage Backend and support default secret provider
  cmd/secret-storage-backend/README.md
  cmd/secret-storage-backend/main.go
  deploy/kubernetes/charts/secret-storage-backend/.helmignore
  deploy/kubernetes/charts/secret-storage-backend/Chart.yaml
  deploy/kubernetes/charts/secret-storage-backend/templates/_helpers.tpl
  deploy/kubernetes/charts/secret-storage-backend/templates/deployment.yaml
  deploy/kubernetes/charts/secret-storage-backend/templates/hpa.yaml
  deploy/kubernetes/charts/secret-storage-backend/templates/secret.yaml
  deploy/kubernetes/charts/secret-storage-backend/templates/service.yaml
  deploy/kubernetes/charts/secret-storage-backend/templates/serviceaccount.yaml
  deploy/kubernetes/charts/secret-storage-backend/values.yaml
  go.mod
  go.sum
  hack/release-charts.sh
  internal/secret-storage-backend/export_test.go
  internal/secret-storage-backend/fake_provider_test.go
  internal/secret-storage-backend/server.go
  internal/secret-storage-backend/server_test.go
  pkg/hub/api/grpc/storage_backend/client_test.go
Labels: enhancement, area/hub

#652 Refactor hub-js, add value mirroring for specified backend
  hack/gen-grpc-resources.sh
  hack/lint.sh
  hub-js/.eslintignore
  hub-js/.eslintrc.js
  hub-js/.eslintrc.yml
  hub-js/.prettierignore
  hub-js/.prettierrc.json
  hub-js/README.md
  hub-js/graphql/local/examples.graphql
  hub-js/graphql/local/schema.graphql
  hub-js/graphql/public/examples.graphql
  hub-js/graphql/public/schema.graphql
  hub-js/package-lock.json
  hub-js/package.json
  hub-js/proto/storage_backend.proto
  hub-js/src/config.ts
  hub-js/src/generated/grpc/storage_backend.ts
  hub-js/src/index.ts
  hub-js/src/local/index.ts
  hub-js/src/local/mutation/context.ts
  hub-js/src/local/mutation/create-type-instance.ts
  hub-js/src/local/mutation/create-type-instances.ts
  hub-js/src/local/mutation/cypher-errors.ts
  hub-js/src/local/mutation/delete-type-instance.ts
  hub-js/src/local/mutation/lock-type-instances.ts
  hub-js/src/local/mutation/register-built-in-storage.ts
  hub-js/src/local/mutation/unlock-type-instances.ts
  hub-js/src/local/mutation/update-type-instances.ts
  hub-js/src/local/storage/service.ts
  hub-js/src/local/types/type-instance.ts
  hub-js/src/logger.ts
  hub-js/src/public/index.ts
  hub-js/src/schema.ts
  hub-js/src/schema/local.ts
  hub-js/tsconfig.json
  internal/cli/client/hub.go
  pkg/hub/api/graphql/local/models_gen.go
  pkg/hub/api/graphql/local/schema_gen.go
  pkg/hub/api/graphql/public/schema_gen.go
  pkg/hub/api/grpc/storage_backend/storage_backend.pb.go
  pkg/hub/client/client.go
  pkg/hub/client/local/client.go
  pkg/hub/client/local/fields.go
  test/e2e/action_test.go
  test/e2e/hub_test.go
Labels: enhancement, area/hub

#654 Add support for external storages on lock, unlock, update, get, and delete
  .github/workflows/pr-build.yaml
  hub-js/graphql/local/schema.graphql
  hub-js/package-lock.json
  hub-js/package.json
  hub-js/proto/storage_backend.proto
  hub-js/src/generated/grpc/storage_backend.ts
  hub-js/src/index.ts
  hub-js/src/local/index.ts
  hub-js/src/local/mutation/context.ts
  hub-js/src/local/mutation/update-type-instances.ts
  hub-js/src/local/resolver/field/spec-value-field.ts
  hub-js/src/local/resolver/mutation/context.ts
  hub-js/src/local/resolver/mutation/create-type-instance.ts
  hub-js/src/local/resolver/mutation/create-type-instances.ts
  hub-js/src/local/resolver/mutation/cypher-errors.ts
  hub-js/src/local/resolver/mutation/delete-type-instance.ts
  hub-js/src/local/resolver/mutation/lock-type-instances.ts
  hub-js/src/local/resolver/mutation/register-built-in-storage.ts
  hub-js/src/local/resolver/mutation/unlock-type-instances.ts
  hub-js/src/local/resolver/mutation/update-type-instances.ts
  hub-js/src/local/storage/service.ts
  hub-js/src/local/storage/update-args-container.ts
  hub-js/src/local/types/type-instance.ts
  internal/secret-storage-backend/server.go
  internal/secret-storage-backend/server_test.go
  pkg/hub/api/graphql/local/models_gen.go
  pkg/hub/api/graphql/local/schema_gen.go
  pkg/hub/api/graphql/local/update_type_instances_input.go
  pkg/hub/api/grpc/storage_backend/storage_backend.pb.go
  test/e2e/action_test.go
  test/e2e/hub_test.go
Labels: enhancement, WIP, area/hub

#660 Add fake value expectation in e2e test till #657 is not resolved
  test/e2e/action_test.go
Labels: area/hub

#664 Fix Helm Implementation generation for empty objects and arrays in Capact CLI
  internal/cli/manifestgen/helm.go
  internal/cli/manifestgen/testdata/cap.implementation.helm.test-generated-schema.yaml
  internal/cli/manifestgen/testdata/cap.implementation.helm.test.yaml
  internal/cli/manifestgen/testdata/cap.type.helm.test-generated-schema-input-parameters.yaml
Labels: bug, area/cli

#669 Bootstrap Helm storage backend Go app
  Dockerfile
  Makefile
  cmd/helm-storage-backend/README.md
  cmd/helm-storage-backend/main.go
  cmd/secret-storage-backend/main.go
  hack/ci/setup-env.sh
  internal/cli/credstore/keychain_darwin.go
  internal/healthz/healthz_server.go
  internal/helm-storage-backend/release.go
  internal/helm-storage-backend/template.go
Labels: enhancement, area/hub

#662 Fix resolving backend.context in cypher
  hub-js/graphql/local/schema.graphql
  pkg/hub/api/graphql/local/schema_gen.go
Labels: bug, area/hub

#659 Add Storage TypeInstance related validation
  hub-js/package-lock.json
  hub-js/package.json
  hub-js/src/local/storage/backend-schema.ts
  hub-js/src/local/storage/service.ts
  test/e2e/hub_test.go
Labels: enhancement, area/hub

#675 Add Helm chart for Helm backend storage
  deploy/kubernetes/charts/helm-storage-backend/.helmignore
  deploy/kubernetes/charts/helm-storage-backend/Chart.yaml
  deploy/kubernetes/charts/helm-storage-backend/templates/_helpers.tpl
  deploy/kubernetes/charts/helm-storage-backend/templates/deployment.yaml
  deploy/kubernetes/charts/helm-storage-backend/templates/hpa.yaml
  deploy/kubernetes/charts/helm-storage-backend/templates/role.yaml
  deploy/kubernetes/charts/helm-storage-backend/templates/rolebinding.yaml
  deploy/kubernetes/charts/helm-storage-backend/templates/service.yaml
  deploy/kubernetes/charts/helm-storage-backend/templates/serviceaccount.yaml
  deploy/kubernetes/charts/helm-storage-backend/values.yaml
  hack/release-charts.sh
Labels: enhancement, area/hub

#680 Remove no longer needed Hadolint ignore for syntax comment
  Dockerfile
Labels: bug, area/ci

#677 Implement Helm release storage backend
  cmd/helm-storage-backend/main.go
  internal/helm-storage-backend/helm.go
  internal/helm-storage-backend/release.go
  internal/helm-storage-backend/release_test.go
  internal/helm-storage-backend/showcase_test.go
  pkg/runner/cloudsql/create.go
Labels: enhancement, area/hub

#679 Ignore failed pods in tests because of graceful node shutdown for Kubernetes 1.22+
  test/e2e/cluster_test.go
Labels: bug, area/ci

#682 Update gcloud usage
  .github/workflows/branch-build.yaml
  .github/workflows/cluster_integration_tests.yaml
  .github/workflows/make-release.yaml
  .github/workflows/recreate_cluster.yaml
Labels: enhancement, dependencies

#684 Fix names of used secrets on CI
  .github/workflows/branch-build.yaml
  .github/workflows/cluster_integration_tests.yaml
  .github/workflows/recreate_cluster.yaml
Labels: bug

#657 Handle multiple backends for the TypeInstance
  hack/images/jinja2/README.md
  hack/images/jinja2/jinja2-cli/jinja2cli/cli.py
  hack/images/jinja2/jinja2-cli/tests/test_jinja2cli.py
  hack/images/merger/README.md
  hack/images/merger/merger.sh
  hub-js/graphql/local/schema.graphql
  hub-js/src/local/resolver/mutation/delete-type-instance.ts
  hub-js/src/local/resolver/mutation/lock-type-instances.ts
  hub-js/src/local/storage/service.ts
  internal/cli/testing/storage_backend.go
  internal/installation/capact_register.go
  pkg/argo-actions/download_type_instances.go
  pkg/argo-actions/update_type_instances.go
  pkg/argo-actions/upload_type_instances.go
  pkg/hub/api/graphql/local/schema_gen.go
  pkg/runner/common.go
  pkg/runner/helm/helm.go
  pkg/runner/helm/types.go
  pkg/runner/helm/upgrade.go
  pkg/runner/terraform/runner.go
  test/e2e/action_test.go
  test/e2e/cluster_test.go
Labels: enhancement, area/engine, area/hub

#686 Support Helm storage backends in Helm runner
  cmd/helm-runner/README.md
  cmd/helm-runner/example-input/helm-release.yaml
  cmd/helm-runner/example-input/install-args.yaml
  cmd/helm-runner/example-input/upgrade-args.yaml
  internal/helm-storage-backend/template.go
  internal/installation/capact_register.go
  pkg/runner/helm/helm.go
  pkg/runner/helm/install.go
  pkg/runner/helm/output.go
  pkg/runner/helm/types.go
  pkg/runner/helm/upgrade.go
  pkg/sdk/validation/typeinstance.go
Labels: enhancement, area/hub-manifests

#690 Add evict annotation for Helm storage
  deploy/kubernetes/charts/helm-storage-backend/values.yaml
Labels: enhancement

#683 Implement Local Hub integration tests as separate job
  .github/workflows/branch-build.yaml
  .github/workflows/pr-build.yaml
  Makefile
  hack/ci/setup-env.sh
  hack/test-local-hub.sh
  test/e2e/hub_test.go
  test/e2e/public_hub_test.go
  test/local-hub/crud_test.go
  test/local-hub/docker-compose.yml
  test/local-hub/external_storage_backend_test.go
  test/local-hub/input_validation_test.go
  test/local-hub/lock_test.go
Labels: enhancement, area/hub, area/ci
