Repository capactio/capact, pull requests merged in 2022-05, with the labels that each got.

#707 Narrow-down the download TypeInstance details
  cmd/terraform-runner/example-input/args.yml
  cmd/ti-value-fetcher/main.go
  internal/cli/manifestgen/templates/terraform-implementation.yaml.tmpl
  internal/cli/manifestgen/testdata/cap.implementation.terraform.aws.test.yaml
  internal/cli/manifestgen/testdata/cap.implementation.terraform.gcp.test.yaml
  internal/cli/manifestgen/testdata/cap.implementation.terraform.generic.test.yaml
  internal/cli/manifestgen/testdata/cap.implementation.terraform.test.yaml
  pkg/argo-actions/download_type_instances.go
  pkg/runner/terraform/terraform.go
  pkg/runner/terraform/types.go
Labels: enhancement, area/engine

#702 Improve errors messages in creating Action mode
  internal/cli/action/create_opts.go
Labels: bug, area/cli

#706 Fix storage backend ID for TypeInstance from nested workflow
  pkg/hub/client/fake/fake.go
  pkg/sdk/renderer/argo/dedicated_renderer.go
  pkg/sdk/renderer/argo/fixtures_test.go
  pkg/sdk/renderer/argo/renderer_test.go
  pkg/sdk/renderer/argo/testdata/TestRenderHappyPathWithCustomPolicies/CloudSQL_PostgreSQL_installation_with_GCP_SA_injected.golden.yaml
  pkg/sdk/renderer/argo/testdata/TestRenderHappyPathWithCustomPolicies/Mattermost_with_AWS_RDS_install.golden.yaml
  pkg/sdk/renderer/argo/testdata/TestRenderHappyPathWithCustomPolicies/Mattermost_with_CloudSQL_PostgreSQL_installation_with_GCP_SA_injected.golden.yaml
  pkg/sdk/renderer/argo/testdata/TestRenderHappyPathWithCustomPolicies/Mattermost_with_CloudSQL_using_Terraform.golden.yaml
  pkg/sdk/renderer/argo/testdata/TestRenderHappyPathWithCustomPolicies/Mattermost_with_existing_DB_installation.golden.yaml
  pkg/sdk/renderer/argo/testdata/TestRenderHappyPathWithCustomPolicies/Mattermost_workflow_with_storage_backends.golden.yaml
  pkg/sdk/renderer/argo/testdata/TestRenderHappyPathWithCustomPolicies/RDS_installation_with_AWS_SA_and_additional_parameters_injected.golden.yaml
  pkg/sdk/renderer/argo/testdata/TestRenderHappyPathWithCustomPolicies/Workflow_policy_injects_additional_input_-_reference_by_ManifestRef.golden.yaml
  pkg/sdk/renderer/argo/testdata/TestRenderHappyPathWithCustomPolicies/Workflow_policy_injects_additional_input_-_reference_by_alias.golden.yaml
  pkg/sdk/renderer/argo/testdata/hub/implementation/bitnami/postgresql/install-v2.yaml
  pkg/sdk/renderer/argo/testdata/hub/implementation/mattermost/mattermost-team-edition/install-v2.yaml
  pkg/sdk/renderer/argo/testdata/hub/implementation/runner/helm/install-v2.yaml
  pkg/sdk/renderer/argo/testdata/hub/type/containerization/kubernetes/kubeconfig.yaml
  pkg/sdk/renderer/argo/testdata/hub/type/core/storage/neo4j.yaml
  pkg/sdk/renderer/argo/testdata/hub/type/helm/release/storage.yaml
  pkg/sdk/renderer/argo/testdata/hub/type/helm/template/storage.yaml
  pkg/sdk/renderer/argo/testdata/hub/typeinstance/helm-release-storage.yaml
  pkg/sdk/renderer/argo/testdata/hub/typeinstance/helm-template-storage.yaml
Labels: bug, area/engine

#713 Add support for ctx update and attach id for downloaded TypeInstance
  hub-js/src/local/resolver/mutation/update-type-instances.ts
  hub-js/src/local/storage/service.ts
  pkg/argo-actions/download_type_instances.go
  pkg/argo-actions/update_type_instances.go
  test/e2e/action_test.go
  test/e2e/e2e_suite_test.go
  test/local-hub/external_storage_backend_test.go
Labels: enhancement, area/engine, area/hub

#714 Do not compress darwin arm64 binary
  .goreleaser.yml
  hack/compress-release-binary.sh
Labels: bug, area/cli

#719 Add act wait command
  cmd/cli/cmd/action/action.go
  cmd/cli/cmd/action/wait.go
  cmd/cli/docs/capact_action.md
  cmd/cli/docs/capact_action_wait.md
  internal/cli/action/wait.go
Labels: enhancement, area/cli

#720 Stream the output in Terraform runner
  cmd/terraform-runner/README.md
  cmd/terraform-runner/example-input/apply-args.yml
  cmd/terraform-runner/example-input/cloudsql.tgz
  cmd/terraform-runner/example-input/destroy-args.yml
  cmd/terraform-runner/example-input/main.tf
  go.mod
  go.sum
  pkg/runner/terraform/runner.go
  pkg/runner/terraform/terraform.go
  pkg/runner/terraform/tfcmd.go
Labels: enhancement, area/hub-manifests

#722 Add act logs command
  cmd/cli/cmd/action/action.go
  cmd/cli/cmd/action/logs.go
  cmd/cli/cmd/root.go
  cmd/cli/docs/capact.md
  cmd/cli/docs/capact_action.md
  cmd/cli/docs/capact_action_create.md
  cmd/cli/docs/capact_action_delete.md
  cmd/cli/docs/capact_action_get.md
  cmd/cli/docs/capact_action_logs.md
  cmd/cli/docs/capact_action_run.md
  cmd/cli/docs/capact_action_wait.md
  cmd/cli/docs/capact_action_watch.md
  cmd/cli/docs/capact_alpha.md
  cmd/cli/docs/capact_alpha_archive-images.md
  cmd/cli/docs/capact_alpha_archive-images_helm.md
  cmd/cli/docs/capact_completion.md
  cmd/cli/docs/capact_config.md
  cmd/cli/docs/capact_config_get-contexts.md
  cmd/cli/docs/capact_config_set-context.md
  cmd/cli/docs/capact_environment.md
  cmd/cli/docs/capact_environment_create.md
  cmd/cli/docs/capact_environment_create_k3d.md
  cmd/cli/docs/capact_environment_create_kind.md
  cmd/cli/docs/capact_environment_delete.md
  cmd/cli/docs/capact_environment_delete_k3d.md
  cmd/cli/docs/capact_environment_delete_kind.md
  cmd/cli/docs/capact_hub.md
  cmd/cli/docs/capact_hub_implementation.md
  cmd/cli/docs/capact_hub_implementation_get.md
  cmd/cli/docs/capact_hub_interface.md
  cmd/cli/docs/capact_hub_interface_browse.md
  cmd/cli/docs/capact_hub_interface_get.md
  cmd/cli/docs/capact_install.md
  cmd/cli/docs/capact_login.md
  cmd/cli/docs/capact_logout.md
  cmd/cli/docs/capact_manifest.md
  cmd/cli/docs/capact_manifest_generate.md
  cmd/cli/docs/capact_manifest_generate_attribute.md
  cmd/cli/docs/capact_manifest_generate_implementation.md
  cmd/cli/docs/capact_manifest_generate_implementation_empty.md
  cmd/cli/docs/capact_manifest_generate_implementation_helm.md
  cmd/cli/docs/capact_manifest_generate_implementation_terraform.md
  cmd/cli/docs/capact_manifest_generate_interface.md
  cmd/cli/docs/capact_manifest_generate_interfacegroup.md
  cmd/cli/docs/capact_manifest_generate_type.md
  cmd/cli/docs/capact_manifest_validate.md
  cmd/cli/docs/capact_policy.md
  cmd/cli/docs/capact_policy_apply.md
  cmd/cli/docs/capact_policy_edit.md
  cmd/cli/docs/capact_policy_get.md
  cmd/cli/docs/capact_typeinstance.md
  cmd/cli/docs/capact_typeinstance_apply.md
  cmd/cli/docs/capact_typeinstance_create.md
  cmd/cli/docs/capact_typeinstance_delete.md
  cmd/cli/docs/capact_typeinstance_edit.md
  cmd/cli/docs/capact_typeinstance_get.md
  cmd/cli/docs/capact_upgrade.md
  cmd/cli/docs/capact_version.md
Labels: enhancement, area/cli

#727 Update Argo Workflows to v3.2.11
  go.mod
  go.sum
Labels: security, area/engine

#728 Improve help message for action logs command
  cmd/cli/cmd/action/logs.go
  cmd/cli/docs/capact_action_logs.md
Labels: area/cli

#729 Use GH_PAT in GoReleaser
  .github/workflows/make-release.yaml
Labels: area/ci

#730 Use a new GitHub token in release job
  .github/workflows/make-release.yaml
Labels: area/ci
